version: '3'
services:
  {{cookiecutter.package_name}}-discord-bot:
    build:
      context: .
    command: python3.8 ./{{cookiecutter.package_name}}/main.py
    restart: unless-stopped
    volumes:
      - .:/workarea
      
  test:
    build: .
    command: pytest -v
    volumes:
      - .:/workarea
    depends_on: 
      - {{cookiecutter.package_name}}-discord-bot